### ISSUE TITLE
incorporate these styles 

### ISSUE THREAD

**Issue by stopfstedt** [ucsf-ckm/moodle-theme-ucsf#82]
```css
@media (max-width: 979px) {
    .navbar .nav-collapse.in {
        background-color: #052049;
    }
    .navbar .nav > li > a:hover {
        color: #000;
    }
    .navbar .nav li.dropdown > a:hover .caret {
        border-top-color: #000;
        border-bottom-color: #000;
    }
    .dropdown-menu > li > a:hover, .dropdown-menu > li > a:focus, .dropdown-submenu:hover > a, .dropdown-submenu:focus > a {
        background: none;
        color: #000;
        background-color: #ededee !important;
    }
    .nav-collapse .nav > li > a, .nav-collapse .dropdown-menu a {
        color: #fff;
    }
}
```
