### ISSUE TITLE
incorporate theme tweaks

### ISSUE THREAD

**Issue by stopfstedt** [ucsf-ckm/moodle-theme-ucsf#85]
another slew  of tweaks

```css
/* LAST UPDATED:  6 July 2017 - 3pm */

/* Widens enrollment methods table */
.boxwidthnormal {
    width: 80%;
}

/* Widens assign roles table */
.path-admin #assignrole {
    width: 80%;
}

/* Widens rightmost column of assign roles table */
.leftalign.roleholder.cell.c3.lastcol {
    width: 20%;
}

/* Increase spacing after user name on profile page */
.userprofile .page-context-header .page-header-headings {
    margin-bottom: 0px;
}


/* Adjusts OU Blog - Blog Usage block text */
.oublog-accordion li .oublog_statsview_title h2 {
    font-size: 1.0em;
    line-height: 20px;
}

.oublog_statsview_content p {
    font-size: 12px;
}

#id_timefilter_commentpoststats {
    font-size: 12px;
}

#id_submitbutton_commentpoststats {
    font-size: 12px;
}
```
